image: seetheprogress/build:v17.06-33988a

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://localhost:2375"
  HUGO_CONTAINER: "seetheprogress/hugo:v0.29.0-63c538"

build pages:about for demo:
  stage: build
  environment: development
  only:
    - master
  script:
  - cd exampleSite
  - find . -name 'config.toml' -type f -exec sed -i -e 's/stats.example.com/stats.seetheprogress.eu/g' -- {} +
  - find . -name 'config.toml' -type f -exec sed -i -e 's/www.example.com/syna-demo.netlify.com/g' -- {} +
  - find . -name 'config.toml' -type f -exec sed -i -e 's/id = "42"/id = "13"/g' -- {} +
  - docker run -u $(id -u):$(id -g) -v $(pwd):/source $HUGO_CONTAINER /hugo -s /source
  - netlify deploy -p public -s $SITE_DEV -t $TOKEN_DEV
