[build]
publish = "public"
command = "hugo -c exampleSite/content --config exampleSite/config.toml --themesDir ../"

[context.production.environment]
HUGO_VERSION = "0.37.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo -c exampleSite/content --config exampleSite/config.toml --themesDir ../ -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.37.1"

[context.branch-deploy]
command = "hugo -c exampleSite/content --config exampleSite/config.toml --themesDir ../ -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.37.1"
