[build]
  base    = "exampleSite"
  publish = "exampleSite/public"
  command = "hugo -t repo"

[context.production.environment]
  HUGO_VERSION = "0.40.3"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo -t repo"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.40.3"

[context.branch-deploy]
  command = "hugo -t repo"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.40.3"
