name = "Syna"
license = "Apache License 2.0"
licenselink = "https://syna.okkur.org/license"
description = "A customizable one to multi page theme for open source projects, companies and freelancers."
homepage = "https://syna.okkur.org"
tags = ["open source", "company", "one-page", "multi-page"]
min_version = 0.48

[author]
  name = "Okkur Labs"
  homepage = "https://about.okkur.org"

# Based on work from David Miller with his startbootstrap-agency theme and the hugo port from digitalcraftsman.
