name = "Syna"
license = "Apache License 2.0"
licenselink = "https://github.com/okkur/syna/blob/master/LICENSE"
description = "A customizable one to multi page theme for open source projects, companies and freelancers."
homepage = "https://syna.okkur.io"
tags = ["modular", "extendable", "react enabled", "single page", "multi page", "blog", "portfolio", "landing"]
min_version = 0.48

[author]
  name = "Okkur Labs"
  homepage = "https://about.okkur.io"

# Based on work from David Miller with his startbootstrap-agency theme and the hugo port from digitalcraftsman.
