# Site settings
baseurl = "https://example.org/"
languageCode = "en-us"
title = "Okkur - Syna"
theme = "syna"
themesDir = "../.."
copyright = "" # default: Copyright $Year $params.name

# Google Analytics tracking
googleAnalytics = ""

[params]
  name = "Okkur Labs"
  description = "Open Source Theme for your next project"
  image = "header.jpg" #default: partial.js

  # Branding options
  [params.branding]
    logoNavigation = "logo.svg"
    textNavigation = "Syna"
    logoFooter = "logo-by.svg"
    textFooter = "Copyright 2017 Syna Authors"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.svg"
    iconFont = ""
    css = []
    js  = []

  # Repository Button
  [params.repoButton]
    url = "https://github.com/okkur/syna"
    text = "Star" # default: "Star"
    icon = "fa-github" # default: "fa-github"

  # Piwik tracking
  [params.analytics.piwik]
    url = "https://stats.example.com"
    id = "42"
    domain = "www.example.com" # Track subdomains via "*.example.com"
    # Optional: Hash for integrity check
    hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

    [[menu.legalFooter]]
      url = "about"
      name = "About Us"
      weight = 10

    [[menu.legalFooter]]
      url = "terms"
      name = "Terms"
      weight = 30
